# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/honza/code/lgk-model/g4application-dicom

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/honza/model/g4application-dicom

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/model/g4application-dicom/CMakeFiles /home/honza/model/g4application-dicom/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/model/g4application-dicom/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dicomPlugin

# Build rule for target.
dicomPlugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dicomPlugin
.PHONY : dicomPlugin

# fast build rule for target.
dicomPlugin/fast:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/build
.PHONY : dicomPlugin/fast

src/DicomData.o: src/DicomData.cc.o
.PHONY : src/DicomData.o

# target to build an object file
src/DicomData.cc.o:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomData.cc.o
.PHONY : src/DicomData.cc.o

src/DicomData.i: src/DicomData.cc.i
.PHONY : src/DicomData.i

# target to preprocess a source file
src/DicomData.cc.i:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomData.cc.i
.PHONY : src/DicomData.cc.i

src/DicomData.s: src/DicomData.cc.s
.PHONY : src/DicomData.s

# target to generate assembly for a file
src/DicomData.cc.s:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomData.cc.s
.PHONY : src/DicomData.cc.s

src/DicomGeometryBuilder.o: src/DicomGeometryBuilder.cc.o
.PHONY : src/DicomGeometryBuilder.o

# target to build an object file
src/DicomGeometryBuilder.cc.o:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomGeometryBuilder.cc.o
.PHONY : src/DicomGeometryBuilder.cc.o

src/DicomGeometryBuilder.i: src/DicomGeometryBuilder.cc.i
.PHONY : src/DicomGeometryBuilder.i

# target to preprocess a source file
src/DicomGeometryBuilder.cc.i:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomGeometryBuilder.cc.i
.PHONY : src/DicomGeometryBuilder.cc.i

src/DicomGeometryBuilder.s: src/DicomGeometryBuilder.cc.s
.PHONY : src/DicomGeometryBuilder.s

# target to generate assembly for a file
src/DicomGeometryBuilder.cc.s:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomGeometryBuilder.cc.s
.PHONY : src/DicomGeometryBuilder.cc.s

src/DicomMessenger.o: src/DicomMessenger.cc.o
.PHONY : src/DicomMessenger.o

# target to build an object file
src/DicomMessenger.cc.o:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomMessenger.cc.o
.PHONY : src/DicomMessenger.cc.o

src/DicomMessenger.i: src/DicomMessenger.cc.i
.PHONY : src/DicomMessenger.i

# target to preprocess a source file
src/DicomMessenger.cc.i:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomMessenger.cc.i
.PHONY : src/DicomMessenger.cc.i

src/DicomMessenger.s: src/DicomMessenger.cc.s
.PHONY : src/DicomMessenger.s

# target to generate assembly for a file
src/DicomMessenger.cc.s:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomMessenger.cc.s
.PHONY : src/DicomMessenger.cc.s

src/DicomPlugin.o: src/DicomPlugin.cc.o
.PHONY : src/DicomPlugin.o

# target to build an object file
src/DicomPlugin.cc.o:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomPlugin.cc.o
.PHONY : src/DicomPlugin.cc.o

src/DicomPlugin.i: src/DicomPlugin.cc.i
.PHONY : src/DicomPlugin.i

# target to preprocess a source file
src/DicomPlugin.cc.i:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomPlugin.cc.i
.PHONY : src/DicomPlugin.cc.i

src/DicomPlugin.s: src/DicomPlugin.cc.s
.PHONY : src/DicomPlugin.s

# target to generate assembly for a file
src/DicomPlugin.cc.s:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomPlugin.cc.s
.PHONY : src/DicomPlugin.cc.s

src/DicomReader.o: src/DicomReader.cc.o
.PHONY : src/DicomReader.o

# target to build an object file
src/DicomReader.cc.o:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomReader.cc.o
.PHONY : src/DicomReader.cc.o

src/DicomReader.i: src/DicomReader.cc.i
.PHONY : src/DicomReader.i

# target to preprocess a source file
src/DicomReader.cc.i:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomReader.cc.i
.PHONY : src/DicomReader.cc.i

src/DicomReader.s: src/DicomReader.cc.s
.PHONY : src/DicomReader.s

# target to generate assembly for a file
src/DicomReader.cc.s:
	$(MAKE) -f CMakeFiles/dicomPlugin.dir/build.make CMakeFiles/dicomPlugin.dir/src/DicomReader.cc.s
.PHONY : src/DicomReader.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dicomPlugin"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/DicomData.o"
	@echo "... src/DicomData.i"
	@echo "... src/DicomData.s"
	@echo "... src/DicomGeometryBuilder.o"
	@echo "... src/DicomGeometryBuilder.i"
	@echo "... src/DicomGeometryBuilder.s"
	@echo "... src/DicomMessenger.o"
	@echo "... src/DicomMessenger.i"
	@echo "... src/DicomMessenger.s"
	@echo "... src/DicomPlugin.o"
	@echo "... src/DicomPlugin.i"
	@echo "... src/DicomPlugin.s"
	@echo "... src/DicomReader.o"
	@echo "... src/DicomReader.i"
	@echo "... src/DicomReader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

