# Basic DICOM example macro
# -------------------------
/component/builtin DefaultWorld
/component/builtin ReferencePhysicsList
/component/builtin MemoryLogging

/component/verbose 1

/conf/setString component.ReferencePhysicsList.listName FTFP_BERT

# /plugin/open libsimplePlugin.so
# /plugin/loadAll simplePlugin

# Load the plugin
/plugin/open dicomPlugin
/plugin/loadAll dicomPlugin

# DICOM images
/dicom/verbose 1
/dicom/addFiles /doc/studium/dicom/CT/*.dcm
/dicom/readFiles # Not necessary
# /dicom/crop 120 136 120 136 0 0
/dicom/loadMaterials /home/honza/model/g4application-dicom/examples/materials-water.json

/conf/setDouble dicom.phantom_center_z 100.0
/conf/setInt dicom.materials.hu_step 100

# Run
/run/initialize

# Show configuration
/conf/print

/run/beamOn 10